version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/nodejs/**/*'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    reviewers:
      - '46ki75'

  - package-ecosystem: 'gradle'
    directories:
      - '/java/**/*'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    reviewers:
      - '46ki75'

  - package-ecosystem: 'cargo'
    directories:
      - '/crates/**/*'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    reviewers:
      - '46ki75'

  - package-ecosystem: 'gomod'
    directories:
      - '/go/**/*'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    reviewers:
      - '46ki75'
