[tool.poetry]
name = "python-module"
version = "0.1.0"
description = ""
authors = ["Shirayuki Chomolungma <shirayuki@46ki75.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
