name: Unit Test (Go)

on:
  push:
    paths:
      - 'go/**'
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - 'go/**'
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go/go_module

    strategy:
      matrix:
        go-version:
          - 1.23.5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Unit Test
        run: go test -cover
