name: Unit Test (Rust)

on:
  push:
    paths:
      - 'crates/**'
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - 'crates/**'
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: crates/rust-crate

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run unit tests
        run: cargo test --lib
